# Generated by Django 5.2.5 on 2025-08-26 07:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_announcement_calendarevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="students",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"role": "student"},
                related_name="enrolled_subjects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
